import os
import re
import uuid
import json
from datetime import datetime
from fastapi import FastAPI, HTTPException, status
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field

from backend.generator import generate_variants
from backend.checker import scan_domains
from backend.scoring import score_domain

# Domain Validation Regex: alphanumeric labels separated by dots, with a TLD of >= 2 chars
DOMAIN_REGEX = re.compile(
    r'^([a-z0-9]+(-[a-z0-9]+)*\.)+[a-z]{2,}$',
    re.IGNORECASE
)

# Parse environment-variable-based CORS origins
app = FastAPI(
    title="Sentinel Domain Watch API",
    description="Brand protection tool that detects likely phishing/typosquat domains targeting a brand."
)

frontend_url = os.environ.get("FRONTEND_URL")
allowed_origins = ["http://localhost:5173"]
if frontend_url:
    allowed_origins.append(frontend_url)

app.add_middleware(
    CORSMiddleware,
    allow_origins=allowed_origins,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# In-memory progress/result cache
ACTIVE_SCANS = {}

class ScanRequest(BaseModel):
    domain: str = Field(..., description="The brand target domain (e.g. examplebank.com)")
    scan_id: str = Field(None, description="Optional unique identifier generated by the client to track scan progress")

def is_valid_domain(domain: str) -> bool:
    """
    Validates if a domain string conforms to a plausible format.
    """
    if not domain:
        return False
    domain = domain.strip().lower()
    return bool(DOMAIN_REGEX.match(domain))

@app.post("/api/scan")
def run_scan(request: ScanRequest):
    domain = request.domain.strip().lower()
    if not is_valid_domain(domain):
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Invalid domain format. Please provide a valid domain (e.g., examplebank.com) without protocol or paths."
        )

    # Use client scan_id or default to domain name
    scan_key = request.scan_id if request.scan_id else domain

    # Manage memory cache size
    if len(ACTIVE_SCANS) > 200:
        oldest_keys = list(ACTIVE_SCANS.keys())[:100]
        for k in oldest_keys:
            ACTIVE_SCANS.pop(k, None)

    # 1. Generate candidate typosquat variants
    variants = generate_variants(domain)
    total_count = len(variants)

    # Initialize progress tracker
    ACTIVE_SCANS[scan_key] = {
        "domain": domain,
        "status": "running",
        "checked": 0,
        "total": total_count,
        "flagged_count": 0,
        "unknown_count": 0
    }

    if total_count == 0:
        ACTIVE_SCANS[scan_key]["status"] = "completed"
        return {
            "domain_scanned": domain,
            "total_variants_checked": 0,
            "flagged_count": 0,
            "unknown_count": 0,
            "results": []
        }

    try:
        # Progress callback updated by individual thread completion
        def progress_callback(checked: int, total: int):
            if scan_key in ACTIVE_SCANS:
                ACTIVE_SCANS[scan_key]["checked"] = checked

        # 2. Verify variants in parallel
        scan_results = scan_domains(variants, progress_callback=progress_callback)

        # 3. Compute risk scores
        scored_results = []
        flagged_count = 0
        unknown_count = 0
        scan_time = datetime.now()

        for res in scan_results:
            scored = score_domain(res, domain, scan_time=scan_time)
            scored_results.append(scored)

            # Count flagged and unknown cases
            dns_resolves = scored["dns_resolves"]
            cert_status = scored["certificate_status"]
            if dns_resolves or cert_status == "confirmed":
                flagged_count += 1
            elif cert_status == "unknown":
                unknown_count += 1

        # Sort results by risk score descending
        scored_results.sort(key=lambda x: x["risk_score"], reverse=True)

        # Finalize cache entry
        ACTIVE_SCANS[scan_key].update({
            "status": "completed",
            "checked": total_count,
            "flagged_count": flagged_count,
            "unknown_count": unknown_count
        })

        return {
            "domain_scanned": domain,
            "total_variants_checked": total_count,
            "flagged_count": flagged_count,
            "unknown_count": unknown_count,
            "results": scored_results
        }

    except Exception as e:
        if scan_key in ACTIVE_SCANS:
            ACTIVE_SCANS[scan_key].update({
                "status": "failed",
                "error": str(e)
            })
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Scan execution failed: {str(e)}"
        )

@app.get("/api/scan/progress/{scan_key}")
def get_scan_progress(scan_key: str):
    """
    Returns the real-time scanning progress for a given scan key.
    """
    progress = ACTIVE_SCANS.get(scan_key)
    if not progress:
        # Fallback to search by domain
        for k, v in ACTIVE_SCANS.items():
            if v.get("domain") == scan_key:
                return v
        return {
            "domain": None,
            "status": "not_started",
            "checked": 0,
            "total": 0,
            "flagged_count": 0,
            "unknown_count": 0
        }
    return progress


if __name__ == "__main__":
    import uvicorn
    import os
    port = int(os.environ.get("PORT", 8000))
    uvicorn.run("main:app", host="0.0.0.0", port=port)
